name: CI

on:
  push:
    branches: [main, develop, 'feature/**']
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Compilar firmware ESP32
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compilar firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0.1
          target: esp32
          path: firmware
